### ISSUE TITLE
Collection of review remarks 

### ISSUE THREAD

**Issue by heluna** [hifis-net/RSD-as-a-service#24]
I played a little arround and want to leave some notes and questions:

- [x] depending on the curation policy (not yet known to me): How do you make sure, that a keyword for allocation to a Helmholtz research area (e.g. Earth and Environmen) is actually assigned? I guess you use that for the discovery filter on the main page?

Software discovery page:
- [x] I'd recommend to place another page shifter (1–12 of 20<  >) at the bottom of the overview, or automatically load more entries when scolling down. I initally thought the first 12 were all entries. https://github.com/research-software-directory/RSD-as-a-service/issues/446
- [x] Are there going to be a more elaborated filter options (e.g. facetted filters based on keywords, license, organisation - or any othe structured information available)? I remember in the NL version there has something been like that - but I can't find it there anymore.

Software entry  form:
- [x] if I enter keyword (existing or new), they are currently not saved 
- [x] maybe there is also a controlled vocabulary for the "role" of people contributing you could use? (e.g like from [DataCite Contributor Role](https://support.datacite.org/docs/datacite-metadata-schema-v44-recommended-and-optional-properties#7a-contributortype) or [ISO19115 CI_RoleCode](https://standards.iso.org/iso/19115/resources/Codelists/gml/CI_RoleCode.xml)  ) https://github.com/research-software-directory/RSD-as-a-service/issues/450
- [x] Maintainer invitation: The text in the mail should provide a little more context. At least that "become a maintainer at the Helmholtz Research Software Directory" or alike, otherwise you can just get from the URL where you should be maintaining something. https://github.com/research-software-directory/RSD-as-a-service/issues/451

Project entry form:
- [x] If I add a very large picture, it is not scaled to fit the display area https://github.com/research-software-directory/RSD-as-a-service/issues/452
- [x] like in software form, keywords are not saved
- [x] The ERC classification is displayed strage in the Detail view: I  shows some rather meaningless classification code ("PE", "PE10") and just on mouse over you can access the classification name/description. It would be better to show it als "Physical Science and Engineering" like in the entry form. https://github.com/research-software-directory/RSD-as-a-service/issues/453
- [x] What is the difference between "Impact" and "Output"? https://github.com/research-software-directory/RSD-as-a-service/discussions/454
- [x] #27
- [x] in the NL version I see that the Classification codes have also a grey background, this seems also the same color in our version #29 
- [x] when I went away from the unpublished Project, to link it to a published software, it was kind of unintuitive to find the way back to the unpublished project. I didn't expect it to be under my profile picture, just found it by searching for it. I would have expected to find it flagged as unplublished when pressing "projects" at the top ribbon. https://github.com/research-software-directory/RSD-as-a-service/issues/455

Hope that helps, otherwise very nice :)

/edit by @cmeessen: referenced issues

**Comment by cmeessen** [comment]
Dear @heluna,

thank you very much for your extended review comments. There are a few points that were already fixed, but let's go through the points one by one:

> depending on the curation policy (not yet known to me): How do you make sure, that a keyword for allocation to a Helmholtz research area (e.g. Earth and Environmen) is actually assigned? I guess you use that for the discovery filter on the main page?

Indeed, we are going to use the keywords to filter by research field (implemented as of today). However, this will only be a temporary solution. We are planning to add a dedicated property "Research field" for each software, that will allow only one of the six research fields. This property will be mandatory upon publishing the software in the Helmholtz RSD.

> I'd recommend to place another page shifter (1–12 of 20< >) at the bottom of the overview, or automatically load more entries when scolling down. I initally thought the first 12 were all entries.

Thank you, we have had this feedback multiple times by now. I added an issue in the upstream repository: https://github.com/research-software-directory/RSD-as-a-service/issues/446

> Are there going to be a more elaborated filter options (e.g. facetted filters based on keywords, license, organisation - or any othe structured information available)? I remember in the NL version there has something been like that - but I can't find it there anymore.

Yes, the [old version](https://research-software.nl) had a list of available filters on the left. I cannot speak for the netherlands eScience center, but as far as I know, more filter options are planned.

> if I enter keyword (existing or new), they are currently not saved

This has already been fixed. We deployed the latest version of the RSD to the HZDR Staging instance yesterday evening (sorry, because of some changes to the database, we had to reset the staging server and remove the test projects/software you added).

> maybe there is also a controlled vocabulary for the "role" of people contributing you could use? (e.g like from DataCite Contributor Role or ISO19115 CI_RoleCode )

Very good idea, I created a new issue upstream: https://github.com/research-software-directory/RSD-as-a-service/issues/450

> Maintainer invitation: The text in the mail should provide a little more context. At least that "become a maintainer at the Helmholtz Research Software Directory" or alike, otherwise you can just get from the URL where you should be maintaining something.

Good point, I opened an issue upstream too (https://github.com/research-software-directory/RSD-as-a-service/issues/451). Long term it is planned that the eMail will be sent by the RSD itself.

> If I add a very large picture, it is not scaled to fit the display area

Yes, the picture area was initially designed for representative images only and not for logos. We discussed today how to solve this and will come up with a solution: https://github.com/research-software-directory/RSD-as-a-service/issues/452

> like in software form, keywords are not saved

Already fixed, see above.

> The ERC classification is displayed strage in the Detail view: I shows some rather meaningless classification code ("PE", "PE10") and just on mouse over you can access the classification name/description. It would be better to show it als "Physical Science and Engineering" like in the entry form.

Yes, I remember this was discussed in the team a while ago too. I created a new issue: https://github.com/research-software-directory/RSD-as-a-service/issues/453

> What is the difference between "Impact" and "Output"?

Good point :) I opened a new thread in the Q&A Section of the discussions in the upstream repo: https://github.com/research-software-directory/RSD-as-a-service/discussions/454

> The "Status bar"  on top of the Start/End date is kind of hidden because of same background color. In Starting mode you can see no bar at all, in "running" you just see the blue part.

This is a very good hint. I converted it to an issue (which is also the reason why there is a modification in your comment), and this may have to be addressed upstream too.

> in the NL version I see that the Classification codes have also a grey background, this seems also the same color in our version

:+1: this one also deserves a new issue: #29 

> when I went away from the unpublished Project, to link it to a published software, it was kind of unintuitive to find the way back to the unpublished project. I didn't expect it to be under my profile picture, just found it by searching for it. I would have expected to find it flagged as unplublished when pressing "projects" at the top ribbon.

Good idea, I forwarded this one to the upstream repository too: https://github.com/research-software-directory/RSD-as-a-service/issues/455

That were all points I believe. Thank you very much, we are glad you liked the overall experience and will include your suggestions in the further development :)

**Comment by cmeessen** [comment]
I am closing this issue, since all points were addressed or now have their own issues.

One more time, thank you very much for the valuable feedback :)
